<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3a45d0291751e387991440aa2b6ce4a2
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PagSeguro\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PagSeguro\\' => 
        array (
            0 => __DIR__ . '/..' . '/pagseguro/pagseguro-php-sdk/source',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3a45d0291751e387991440aa2b6ce4a2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3a45d0291751e387991440aa2b6ce4a2::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
