tinyMCE.addI18n('pt.advimage_dlg',{
tab_general:"Geral",
tab_appearance:"Apar\u00EAncia",
tab_advanced:"Avan\u00E7ado",
general:"Geral",
title:"T\u00EDtulo",
preview:"Pre-visualiza\u00E7\u00E3o",
constrain_proportions:"Tamanho Proporcional",
langdir:"Language direction",
langcode:"Language code",
long_desc:"Long description link",
style:"Style",
classes:"Classes",
ltr:"Esquerda para direita",
rtl:"Direita para esquerda",
id:"Id",
map:"Image map",
swap_image:"Swap image",
alt_image:"Imagem alternativa",
mouseover:"para mouse over",
mouseout:"para mouse out",
misc:"Diversos",
example_img:"Pre-visualiza\u00E7\u00E3o",
missing_alt:"Tem certeza que deseja continuar sem acrescentar uma descri\u00E7\u00E3o na imagem? Isto pode gerar problemas de acessibilidade em alguns browsers!",
dialog_title:"Inserir/editar imagem",
src:"Endere\u00E7o da Imagem (sempre a partir da pasta de seu manual helpcase):",
src_ex:"Ex: img.gif ou pasta/img.gif",
alt:"Imagem descri\u00E7\u00E3o",
list:"Imagem lista",
border:"Borda",
dimensions:"Dimens\u00F5es",
vspace:"Espa\u00E7amento vertical",
hspace:"Espa\u00E7amento horizontal",
align:"Alinhamento",
align_baseline:"Baseline",
align_top:"Top",
align_middle:"Middle",
align_bottom:"Bottom",
align_texttop:"Text top",
align_textbottom:"Text bottom",
align_left:"Esquerda",
align_right:"Direita",
image_list:"Image list"
});