<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'chatapi\\WhatsApp\\Client' => $vendorDir . '/chatapi/whatsapp/src/Client.php',
);
