Nm_erro = {
  "lang_jscr_dcml" : "Desatinné čísla",
  "lang_jscr_decm" : "Desatina sekundy",
  "lang_jscr_hour" : "Hodina",
  "lang_jscr_iday" : "Deň",
  "lang_jscr_intg" : "Celé čísla a",
  "lang_jscr_ivcr" : "Neplatné číslo kreditnej karty",
  "lang_jscr_ivdt" : "Neplatné údaje:",
  "lang_jscr_ivem" : "Neplatný Email:",
  "lang_jscr_ivnb" : "Neplatné celé číslo",
  "lang_jscr_ivtm" : "Neplatný čas:",
  "lang_jscr_ivv2" : "Neplatný údaj",
  "lang_jscr_ivvl" : "Neplatné desatinné číslo",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Najvyšší dátum",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Najnižší dátum",
  "lang_jscr_mint" : "Minúty",
  "lang_jscr_mnth" : "Mesiac",
  "lang_jscr_msfr" : "Formulár(pole formulára) musí byt pomenovaný/á",
  "lang_jscr_mslg" : "Chýbajúci login;",
  "lang_jscr_msob" : "Objekt formulára musí byť pomenovaný.",
  "lang_jscr_mxdg" : "Počet čísel prekročil predpokladané množstvo",
  "lang_jscr_mxvl" : "Maximálna dĺžka prekročená",
  "lang_jscr_nnum" : "Položka je numerická",
  "lang_jscr_nvlf" : "Znamienko mínus musí byť vľavo od hodnoty.",
  "lang_jscr_reqr" : "Požadovaná položka",
  "lang_jscr_secd" : "Sekundy",
  "lang_jscr_wfix" : "- Chcete opraviť?"
};

//-------- Mens USR
