Nm_erro = {
  "lang_jscr_dcml" : "Desimaler",
  "lang_jscr_decm" : "Et tiendedels sekund",
  "lang_jscr_hour" : "Time",
  "lang_jscr_iday" : "Dag",
  "lang_jscr_intg" : "Hele tall og",
  "lang_jscr_ivcr" : "Ugyldig kreditkortnummer",
  "lang_jscr_ivdt" : "Ugyldige data:",
  "lang_jscr_ivem" : "Ugyldig e-post:",
  "lang_jscr_ivnb" : "Ugyldig heltall:",
  "lang_jscr_ivtm" : "Ugyldig klokkeslett:",
  "lang_jscr_ivv2" : "Ugyldige data:",
  "lang_jscr_ivvl" : "Ugyldig desimal:",
  "lang_jscr_maxm" : "Maks.",
  "lang_jscr_maxm_date" : "Maksimum data",
  "lang_jscr_minm" : "Min.",
  "lang_jscr_minm_date" : "Minimum data",
  "lang_jscr_mint" : "Minutter",
  "lang_jscr_mnth" : "Måned",
  "lang_jscr_msfr" : "Form må ha et navn",
  "lang_jscr_mslg" : "login mangler;",
  "lang_jscr_msob" : "Dette Form objektet må ha et navn",
  "lang_jscr_mxdg" : "Antall sifre overskrider det forventede",
  "lang_jscr_mxvl" : "Maks. lengde overskredet",
  "lang_jscr_nnum" : "Feltet er numerisk",
  "lang_jscr_nvlf" : "Det negative tegnet må være på venstre side av verdien",
  "lang_jscr_reqr" : "Obligatorisk felt",
  "lang_jscr_secd" : "Sekunder",
  "lang_jscr_wfix" : "- ønsker du å endre?"
};

//-------- Mens USR
