Nm_erro = {
  "lang_jscr_dcml" : "Decimals",
  "lang_jscr_decm" : "Tenth of a second",
  "lang_jscr_hour" : "Hour",
  "lang_jscr_iday" : "Day",
  "lang_jscr_intg" : "Integers and",
  "lang_jscr_ivcr" : "Invalid Credit Card Number",
  "lang_jscr_ivdt" : "Invalid Data:",
  "lang_jscr_ivem" : "Invalid Email",
  "lang_jscr_ivnb" : "Invalid integer",
  "lang_jscr_ivtm" : "Invalid Time:",
  "lang_jscr_ivv2" : "Invalid Data:",
  "lang_jscr_ivvl" : "Invalid decimal",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Maximum Date",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Minimum Date",
  "lang_jscr_mint" : "Minutes",
  "lang_jscr_mnth" : "Month",
  "lang_jscr_msfr" : "The Form must have a name",
  "lang_jscr_mslg" : "Username missing;",
  "lang_jscr_msob" : "This Form object must have a name",
  "lang_jscr_mxdg" : "Number of digits exceeds the limit",
  "lang_jscr_mxvl" : "Max length exceeded",
  "lang_jscr_nnum" : "The field is numeric",
  "lang_jscr_nvlf" : "The negative sign must be on value's left",
  "lang_jscr_reqr" : "Required field",
  "lang_jscr_secd" : "Seconds",
  "lang_jscr_wfix" : "- do you want to correct it ?"
};

//-------- Mens USR
