Nm_erro = {
  "lang_jscr_dcml" : "Decimalke",
  "lang_jscr_decm" : "Desetinka sekunde",
  "lang_jscr_hour" : "Ura",
  "lang_jscr_iday" : "Dan",
  "lang_jscr_intg" : "Številke in",
  "lang_jscr_ivcr" : "Napačna številka kreditne kartice",
  "lang_jscr_ivdt" : "Napačen podatek:",
  "lang_jscr_ivem" : "Napačen Email:",
  "lang_jscr_ivnb" : "Napačna številka",
  "lang_jscr_ivtm" : "Napačen čas:",
  "lang_jscr_ivv2" : "Napačen podatek:",
  "lang_jscr_ivvl" : "Napačna decimalka",
  "lang_jscr_maxm" : "Maks",
  "lang_jscr_maxm_date" : "Največji datum",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Najmanjši datum",
  "lang_jscr_mint" : "Minute",
  "lang_jscr_mnth" : "Mesec",
  "lang_jscr_msfr" : "Obrazec mora biti poimenovan",
  "lang_jscr_mslg" : "manjka uporabnik;",
  "lang_jscr_msob" : "Ta objekt obrazca mora biti poimenovan",
  "lang_jscr_mxdg" : "Znesek presega pričakovano število številk",
  "lang_jscr_mxvl" : "Največja dolžina je presežena",
  "lang_jscr_nnum" : "Polje je numerično",
  "lang_jscr_nvlf" : "Negativni znak mora biti na levi strani vrednosti",
  "lang_jscr_reqr" : "Zahtevano polje",
  "lang_jscr_secd" : "Sekunde",
  "lang_jscr_wfix" : "- Želite popraviti?"
};

//-------- Mens USR
