Nm_erro = {
  "lang_jscr_dcml" : "Decimals",
  "lang_jscr_decm" : "બીજા દસમી",
  "lang_jscr_hour" : "કલાક",
  "lang_jscr_iday" : "દિવસ",
  "lang_jscr_intg" : "પૂર્ણાંકો અને",
  "lang_jscr_ivcr" : "અમાન્ય ક્રેડિટ કાર્ડ નંબર",
  "lang_jscr_ivdt" : "અમાન્ય ડેટા:",
  "lang_jscr_ivem" : "Invalid Email",
  "lang_jscr_ivnb" : "અમાન્ય પૂર્ણાંક",
  "lang_jscr_ivtm" : "અમાન્ય સમય:",
  "lang_jscr_ivv2" : "અમાન્ય ડેટા:",
  "lang_jscr_ivvl" : "અમાન્ય દશાંશ",
  "lang_jscr_maxm" : "મેક્સ",
  "lang_jscr_maxm_date" : "મહત્તમ તારીખ",
  "lang_jscr_minm" : "મને",
  "lang_jscr_minm_date" : "ન્યુનત્તમ તારીખ",
  "lang_jscr_mint" : "મિનિટ",
  "lang_jscr_mnth" : "મહિનો",
  "lang_jscr_msfr" : "ફોર્મ નામ હોવી જ જોઈએ",
  "lang_jscr_mslg" : "Username missing;",
  "lang_jscr_msob" : "આ ફોર્મ પદાર્થ એક નામ છે જ જોઈએ",
  "lang_jscr_mxdg" : "Number of digits exceeds the limit",
  "lang_jscr_mxvl" : "મહત્તમ લંબાઈ વટાવી",
  "lang_jscr_nnum" : "ક્ષેત્રમાં આંકડાકીય છે",
  "lang_jscr_nvlf" : "નકારાત્મક સહીનુ કિંમત ડાબી પર હોવા જ જોઈએ",
  "lang_jscr_reqr" : "આવશ્યક ક્ષેત્ર",
  "lang_jscr_secd" : "સેકન્ડ્સ",
  "lang_jscr_wfix" : "- do you want to correct it ?"
};

//-------- Mens USR
