Nm_erro = {
  "lang_jscr_dcml" : "Decimales",
  "lang_jscr_decm" : "Décima de segundo",
  "lang_jscr_hour" : "Hora",
  "lang_jscr_iday" : "Día",
  "lang_jscr_intg" : "Enteros",
  "lang_jscr_ivcr" : "¡Tarjeta no válida!",
  "lang_jscr_ivdt" : "Datos no válidos:",
  "lang_jscr_ivem" : "E-mail no válido:",
  "lang_jscr_ivnb" : "¡Número no válido!",
  "lang_jscr_ivtm" : "Hora no válida:",
  "lang_jscr_ivv2" : "Valor no válido:",
  "lang_jscr_ivvl" : "¡Valor no válido!",
  "lang_jscr_maxm" : "Máx.",
  "lang_jscr_maxm_date" : "Fecha máxima",
  "lang_jscr_minm" : "Min.",
  "lang_jscr_minm_date" : "Fecha mínima",
  "lang_jscr_mint" : "Minutos",
  "lang_jscr_mnth" : "Mes",
  "lang_jscr_msfr" : "¡Faltó definir un nombre para el formulario!",
  "lang_jscr_mslg" : "Faltó Login;",
  "lang_jscr_msob" : "¡Faltó definir un nombre para este objeto del Formulario!",
  "lang_jscr_mxdg" : "La cantidad de dígitos superó lo previsto",
  "lang_jscr_mxvl" : "Límite máximo excedido",
  "lang_jscr_nnum" : "¡Campo con datos no numéricos!",
  "lang_jscr_nvlf" : "El signo negativo debe estar del lado izquierdo del valor",
  "lang_jscr_reqr" : "¡Campo requerido!",
  "lang_jscr_secd" : "Segundos",
  "lang_jscr_wfix" : "¿Desea corregir?"
};

//-------- Mens USR
