Nm_erro = {
  "lang_jscr_dcml" : "Perpuluhan",
  "lang_jscr_decm" : "Kesepuluh satu saat",
  "lang_jscr_hour" : "Jam",
  "lang_jscr_iday" : "Hari",
  "lang_jscr_intg" : "Integer dan",
  "lang_jscr_ivcr" : "Nombor Kad Kredit Tidak Sah",
  "lang_jscr_ivdt" : "Data Tidak Sah:",
  "lang_jscr_ivem" : "Email Tidak Sah:",
  "lang_jscr_ivnb" : "Integer Tidak Sah:",
  "lang_jscr_ivtm" : "Masa Tidak Sah:",
  "lang_jscr_ivv2" : "Data Tidak Sah:",
  "lang_jscr_ivvl" : "Perpuluhan Tidak Sah:",
  "lang_jscr_maxm" : "Maks",
  "lang_jscr_maxm_date" : "Maksimum Tarikh",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Minimum Tarikh",
  "lang_jscr_mint" : "Minit",
  "lang_jscr_mnth" : "Bulan",
  "lang_jscr_msfr" : "Borang mesti mempunyai nama",
  "lang_jscr_mslg" : "Nama Pengguna hilang;",
  "lang_jscr_msob" : "Objek Borang ini mesti mempunyai nama",
  "lang_jscr_mxdg" : "Jumlah digit melebihi jangkaan",
  "lang_jscr_mxvl" : "Melebihi panjang maks",
  "lang_jscr_nnum" : "Bahagian ini adalah angka",
  "lang_jscr_nvlf" : "Tanda negatif mesti berada di sebelah kiri nilai",
  "lang_jscr_reqr" : "Bahagian diperlukan",
  "lang_jscr_secd" : "Saat",
  "lang_jscr_wfix" : "-Adakah anda ingin membetulkan?"
};

//-------- Mens USR
