Nm_erro = {
  "lang_jscr_dcml" : "Kümnendarvud",
  "lang_jscr_decm" : "Kümnendik sekundit",
  "lang_jscr_hour" : "Tund",
  "lang_jscr_iday" : "Päev",
  "lang_jscr_intg" : "Täisarvud ja",
  "lang_jscr_ivcr" : "Kehtetu krediitkardi number",
  "lang_jscr_ivdt" : "Kehtetu andmed",
  "lang_jscr_ivem" : "Kehtetu E-post",
  "lang_jscr_ivnb" : "Kehtetu täisarv",
  "lang_jscr_ivtm" : "Kehtetu Aeg",
  "lang_jscr_ivv2" : "Kehtetud andmed",
  "lang_jscr_ivvl" : "Kehtetu kümnendik",
  "lang_jscr_maxm" : "Maksimum",
  "lang_jscr_maxm_date" : "Maksimaalne kuupäev",
  "lang_jscr_minm" : "Miinimum",
  "lang_jscr_minm_date" : "Minimaalne kuupäev",
  "lang_jscr_mint" : "Minutid",
  "lang_jscr_mnth" : "Kuu",
  "lang_jscr_msfr" : "Sel vormil peab olema nimi",
  "lang_jscr_mslg" : "Sisselogimine puudub",
  "lang_jscr_msob" : "Sellel vormi objektil peab olema nimi",
  "lang_jscr_mxdg" : "Numbrite arv ületas oodatud arvu",
  "lang_jscr_mxvl" : "Maksimaalne pikkus ületatud",
  "lang_jscr_nnum" : "See lahter on numbriline",
  "lang_jscr_nvlf" : "Negatiivne tähis peab olema väärtusest vasakul",
  "lang_jscr_reqr" : "Nõutud väli",
  "lang_jscr_secd" : "Sekundid",
  "lang_jscr_wfix" : "Kas te soovite parandada?"
};

//-------- Mens USR
