Nm_erro = {
  "lang_jscr_dcml" : "عشرى",
  "lang_jscr_decm" : "عشر الثانية",
  "lang_jscr_hour" : "ساعة",
  "lang_jscr_iday" : "يوم",
  "lang_jscr_intg" : "أعداد صحيحة و",
  "lang_jscr_ivcr" : "رقم بطاقة الائتمان غير صحيح",
  "lang_jscr_ivdt" : "بيانات خاطئة",
  "lang_jscr_ivem" : "بريد إلكتروني غير صحيح",
  "lang_jscr_ivnb" : "عدد خاطئ",
  "lang_jscr_ivtm" : "وقت غير صحيح",
  "lang_jscr_ivv2" : "بيانات خاطئة",
  "lang_jscr_ivvl" : "كسر غير صحيح",
  "lang_jscr_maxm" : "الأقصى",
  "lang_jscr_maxm_date" : "التاريخ الأقصى",
  "lang_jscr_minm" : "الأدنى",
  "lang_jscr_minm_date" : "التاريخ الأدنى",
  "lang_jscr_mint" : "دقائق",
  "lang_jscr_mnth" : "شهر",
  "lang_jscr_msfr" : "يجب أن يكون للنموذج اسم",
  "lang_jscr_mslg" : "لم يتم تسجيل الدخول",
  "lang_jscr_msob" : "هذا النموذج يجب أن يكون له إسم",
  "lang_jscr_mxdg" : "عدد الأرقام تجاوز العدد المسموح",
  "lang_jscr_mxvl" : "تم تجاوز الحد الأقصى",
  "lang_jscr_nnum" : "هذاه الخانة عددية",
  "lang_jscr_nvlf" : "علامة السالب يجب أن تكون يسار القيمة",
  "lang_jscr_reqr" : "خانة مطلوبة",
  "lang_jscr_secd" : "ثواني",
  "lang_jscr_wfix" : "هل تريد التصحيح؟"
};

//-------- Mens USR
