Nm_erro = {
  "lang_jscr_dcml" : "Δεκαδικά",
  "lang_jscr_decm" : "Δέκατο του δευτερολέπτου",
  "lang_jscr_hour" : "Ώρα",
  "lang_jscr_iday" : "Ημέρα",
  "lang_jscr_intg" : "Ακέραιοι αριθμοί και",
  "lang_jscr_ivcr" : "Μη έγκυρος Αριθμός Πιστωτικής Κάρτας",
  "lang_jscr_ivdt" : "Μη έγκυρα δεδομένα:",
  "lang_jscr_ivem" : "Μη έγκυρο E-Mail :",
  "lang_jscr_ivnb" : "Άκυρος ακέραιος αριθμός",
  "lang_jscr_ivtm" : "Άκυρος Χρόνος:",
  "lang_jscr_ivv2" : "Άκυρη Ημερομηνία:",
  "lang_jscr_ivvl" : "Άκυρος δεκαδικός",
  "lang_jscr_maxm" : "Μέγ.",
  "lang_jscr_maxm_date" : "Μέγιστη Ημερομηνία",
  "lang_jscr_minm" : "Ελάχ.",
  "lang_jscr_minm_date" : "Ελάχιστη Ημερομηνία",
  "lang_jscr_mint" : "Λεπτά",
  "lang_jscr_mnth" : "Μήνας",
  "lang_jscr_msfr" : "Η Φόρμα πρέπει να διαθέτει ονομασία",
  "lang_jscr_mslg" : "login λείπει",
  "lang_jscr_msob" : "Αυτή η Φόρμα αντικειμένου πρέπει να διαθέτει ονομασία",
  "lang_jscr_mxdg" : "Αριθμός ψηφίων μεγαλύτερος του προβλεπόμενου",
  "lang_jscr_mxvl" : "Υπέρβαση μέγιστου μήκους",
  "lang_jscr_nnum" : "Το πεδίο είναι αριθμητικό",
  "lang_jscr_nvlf" : "Η ένδειξη αρνητικού πρέπει να βρίσκεται στα αριστερά του αριθμού",
  "lang_jscr_reqr" : "Υποχρεωτικό πεδίο",
  "lang_jscr_secd" : "Δευτερόλεπτα",
  "lang_jscr_wfix" : "- Θέλετε να προβείτε σε διόρθωση;"
};

//-------- Mens USR
