Nm_erro = {
  "lang_jscr_dcml" : "Decimale",
  "lang_jscr_decm" : "Desetinke sekunde",
  "lang_jscr_hour" : "Sat",
  "lang_jscr_iday" : "Dan",
  "lang_jscr_intg" : "Cijeli brojevi i",
  "lang_jscr_ivcr" : "Neispravan broj kreditne kartice",
  "lang_jscr_ivdt" : "Neispravni podaci :",
  "lang_jscr_ivem" : "Neisprevan Email :",
  "lang_jscr_ivnb" : "Neispravan broj",
  "lang_jscr_ivtm" : "Nesipravno vrijeme:",
  "lang_jscr_ivv2" : "Neispravan podatak :",
  "lang_jscr_ivvl" : "Neispravna decimala",
  "lang_jscr_maxm" : "Maksimum",
  "lang_jscr_maxm_date" : "Maksimalan datum",
  "lang_jscr_minm" : "Minimum",
  "lang_jscr_minm_date" : "Minimalan datum",
  "lang_jscr_mint" : "Minute",
  "lang_jscr_mnth" : "Mjesec",
  "lang_jscr_msfr" : "Obrazac mora imati ime",
  "lang_jscr_mslg" : "Prijava nedostaje ;",
  "lang_jscr_msob" : "Ovaj objekt obrazac mora imati ime",
  "lang_jscr_mxdg" : "Iznos brojkama prelazi očekivani",
  "lang_jscr_mxvl" : "Premašena maksimalna dužina",
  "lang_jscr_nnum" : "Polje je numeričko",
  "lang_jscr_nvlf" : "Negativni predznak mora biti na vrijednosti slijeva",
  "lang_jscr_reqr" : "Obavezno polje",
  "lang_jscr_secd" : "Sekunde",
  "lang_jscr_wfix" : "- Želite li se ispraviti ?"
};

//-------- Mens USR
