Nm_erro = {
  "lang_jscr_dcml" : "Десяткові дроби",
  "lang_jscr_decm" : "Десята частка секунди",
  "lang_jscr_hour" : "Година",
  "lang_jscr_iday" : "День",
  "lang_jscr_intg" : "Цілі числа та",
  "lang_jscr_ivcr" : "Невірний номер кредитної картки",
  "lang_jscr_ivdt" : "Невірні дані:",
  "lang_jscr_ivem" : "Невірна електронна адреса",
  "lang_jscr_ivnb" : "Невірне ціле число",
  "lang_jscr_ivtm" : "Невірний час:",
  "lang_jscr_ivv2" : "Невірні дані:",
  "lang_jscr_ivvl" : "Невірні десяткові дроби",
  "lang_jscr_maxm" : "Максимум",
  "lang_jscr_maxm_date" : "Максимальна дата",
  "lang_jscr_minm" : "Мінімум",
  "lang_jscr_minm_date" : "Мінімальна дата",
  "lang_jscr_mint" : "Хвилини",
  "lang_jscr_mnth" : "Місяць",
  "lang_jscr_msfr" : "Форма повинна мати назву",
  "lang_jscr_mslg" : "Логін відсутній",
  "lang_jscr_msob" : "Об'єкт форми повинен мати і'мя",
  "lang_jscr_mxdg" : "Кількість чисел перевищує очікування",
  "lang_jscr_mxvl" : "Максимальная довжина перевищення",
  "lang_jscr_nnum" : "Числове поле",
  "lang_jscr_nvlf" : "Негативний знак повинен бути зліва",
  "lang_jscr_reqr" : "Обов'язкове поле",
  "lang_jscr_secd" : "Секунди",
  "lang_jscr_wfix" : "Ви хочете виправити?"
};

//-------- Mens USR
