Nm_erro = {
  "lang_jscr_dcml" : "Zecimale",
  "lang_jscr_decm" : "Zecime de secundă",
  "lang_jscr_hour" : "Oră",
  "lang_jscr_iday" : "Zi",
  "lang_jscr_intg" : "Intregi şi",
  "lang_jscr_ivcr" : "Numar card de credit eronat",
  "lang_jscr_ivdt" : "Dată eronată:",
  "lang_jscr_ivem" : "Email eronat:",
  "lang_jscr_ivnb" : "Întreg eronat",
  "lang_jscr_ivtm" : "Timp eronat",
  "lang_jscr_ivv2" : "Dată eronată",
  "lang_jscr_ivvl" : "Zecimal eronat",
  "lang_jscr_maxm" : "Maxim",
  "lang_jscr_maxm_date" : "Data maximă",
  "lang_jscr_minm" : "Minim",
  "lang_jscr_minm_date" : "Data minimă",
  "lang_jscr_mint" : "Minute",
  "lang_jscr_mnth" : "Luni",
  "lang_jscr_msfr" : "Formularul trebuie sa aibă un nume",
  "lang_jscr_mslg" : "Autentificarea lipseşte",
  "lang_jscr_msob" : "Acest obiect din formular trebuie sa aibă un nume",
  "lang_jscr_mxdg" : "Mai multe cifre decât este asteptat",
  "lang_jscr_mxvl" : "Lungimea maximă depaşită",
  "lang_jscr_nnum" : "Câmpul este numeric",
  "lang_jscr_nvlf" : "Semnul minus trebuie să fie în stanga valorii",
  "lang_jscr_reqr" : "Câmp necesar",
  "lang_jscr_secd" : "Secunde",
  "lang_jscr_wfix" : "Vreţi să corectaţi?"
};

//-------- Mens USR
