Nm_erro = {
  "lang_jscr_dcml" : "Ondalık Sayılar",
  "lang_jscr_decm" : "Saniyenin onda biri",
  "lang_jscr_hour" : "Saat",
  "lang_jscr_iday" : "Gün",
  "lang_jscr_intg" : "Tam sayılar ve",
  "lang_jscr_ivcr" : "Geçersiz Kredi Karti Numarası",
  "lang_jscr_ivdt" : "Geçersiz Veri:",
  "lang_jscr_ivem" : "Geçersiz E-posta:",
  "lang_jscr_ivnb" : "Geçersiz tam sayı",
  "lang_jscr_ivtm" : "Geçersiz Süre:",
  "lang_jscr_ivv2" : "Geçersiz Veri:",
  "lang_jscr_ivvl" : "Geçersiz ondalık sayı",
  "lang_jscr_maxm" : "Maksimum",
  "lang_jscr_maxm_date" : "Maksimum Tarih",
  "lang_jscr_minm" : "Minimum",
  "lang_jscr_minm_date" : "Minimum Tarih",
  "lang_jscr_mint" : "Dakika",
  "lang_jscr_mnth" : "Ay",
  "lang_jscr_msfr" : "Forma bir ad vermelisiniz",
  "lang_jscr_mslg" : "Giriş yapmalısınız;",
  "lang_jscr_msob" : "Bu Form nesnesine bir ad vermelisiniz",
  "lang_jscr_mxdg" : "Basamak sayısı beklenenin üzerinde çıktı",
  "lang_jscr_mxvl" : "Maksimum uzunluk aşıldı",
  "lang_jscr_nnum" : "Alan sayısal",
  "lang_jscr_nvlf" : "Eksi işaretinin, değerin sol tarafında olması gerekir",
  "lang_jscr_reqr" : "Gerekli alan",
  "lang_jscr_secd" : "Saniye",
  "lang_jscr_wfix" : "- Düzeltmek istiyor musunuz?"
};

//-------- Mens USR
