Nm_erro = {
  "lang_jscr_dcml" : "Decimaler",
  "lang_jscr_decm" : "Tiondels sekund",
  "lang_jscr_hour" : "Timme",
  "lang_jscr_iday" : "Dag",
  "lang_jscr_intg" : "Heltal och",
  "lang_jscr_ivcr" : "Ogiltigt kreditkortsnummer",
  "lang_jscr_ivdt" : "Ogiltiga data:",
  "lang_jscr_ivem" : "Ogiltig e-postadress:",
  "lang_jscr_ivnb" : "Ogiltigt heltal",
  "lang_jscr_ivtm" : "Ogiltig tid:",
  "lang_jscr_ivv2" : "Ogiltiga data:",
  "lang_jscr_ivvl" : "Ogiltig decimal",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Maxdatum",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Minimidatum",
  "lang_jscr_mint" : "Minuter",
  "lang_jscr_mnth" : "Månad",
  "lang_jscr_msfr" : "Formuläret måste ha ett namn",
  "lang_jscr_mslg" : "användarnamn saknas;",
  "lang_jscr_msob" : "Formulärobjektet måste ha ett namn",
  "lang_jscr_mxdg" : "Antalet siffror överstiger förväntat antal",
  "lang_jscr_mxvl" : "Maxlängden har överskridits",
  "lang_jscr_nnum" : "Fältet är numeriskt",
  "lang_jscr_nvlf" : "Minustecknet måste stå till vänster om värdet",
  "lang_jscr_reqr" : "Obligatoriskt fält",
  "lang_jscr_secd" : "Sekunder",
  "lang_jscr_wfix" : "- Vill du ändra?"
};

//-------- Mens USR
