Nm_erro = {
  "lang_jscr_dcml" : "దశాంశాలు",
  "lang_jscr_decm" : "క్షణంలో పదవ భాగం",
  "lang_jscr_hour" : "గంట",
  "lang_jscr_iday" : "దినం",
  "lang_jscr_intg" : "పూర్ణాంకాలు మరియు",
  "lang_jscr_ivcr" : "అమోదయోగ్యం కాని క్రెడిట్  కార్డు సంఖ్య",
  "lang_jscr_ivdt" : "చెల్లని దత్తాంశం",
  "lang_jscr_ivem" : "చెల్లని ఈ మెయిల్",
  "lang_jscr_ivnb" : "చెల్లని పూర్ణాంకం",
  "lang_jscr_ivtm" : "చెల్లని సమయం",
  "lang_jscr_ivv2" : "చెల్లని దత్తాంశం",
  "lang_jscr_ivvl" : "అమోదయోగ్యం కాని దశాంశం",
  "lang_jscr_maxm" : "గరిష్టంగా",
  "lang_jscr_maxm_date" : "గరిష్ఠ తేదీ",
  "lang_jscr_minm" : "అధమంగా",
  "lang_jscr_minm_date" : "అధమమైన తేదీ",
  "lang_jscr_mint" : "నిముషాలు",
  "lang_jscr_mnth" : "మాసం",
  "lang_jscr_msfr" : "ఆకృతికి పేరుండాలి",
  "lang_jscr_mslg" : "లాగిన్  తప్పిపోయింది",
  "lang_jscr_msob" : "ఈ రూపానికి ఒక పేరుండాలి",
  "lang_jscr_mxdg" : "సంఖ్యల మొత్తము ఆపేక్షించినకన్నా అధిగమిస్తోంది",
  "lang_jscr_mxvl" : "గరిష్ఠ ప్రమాణపు నిడివి అధిగమించింది",
  "lang_jscr_nnum" : "క్షేత్రం సంఖ్యా సంబంధమైనది",
  "lang_jscr_nvlf" : "రుణాత్మక చిహ్నం వెలకట్టుకి ఎడుమవైపు ఉండాలి",
  "lang_jscr_reqr" : "అవసరం అయిన క్షేత్రం",
  "lang_jscr_secd" : "క్షణాలు",
  "lang_jscr_wfix" : "మీరు సరిదిద్దాలనుకుంటున్నారా?"
};

//-------- Mens USR
