Nm_erro = {
  "lang_jscr_dcml" : "दशमलव अंक",
  "lang_jscr_decm" : "एक सेकंड का दसवां हिस्सा",
  "lang_jscr_hour" : "घंटा",
  "lang_jscr_iday" : "दिन",
  "lang_jscr_intg" : "पूर्णांक और",
  "lang_jscr_ivcr" : "अवैध क्रेडिट कार्ड नंबर",
  "lang_jscr_ivdt" : "अमान्य डेटा:",
  "lang_jscr_ivem" : "अमान्य ईमेल:",
  "lang_jscr_ivnb" : "अमान्य पूर्णांक",
  "lang_jscr_ivtm" : "अमान्य समय:",
  "lang_jscr_ivv2" : "अमान्य डेटा:",
  "lang_jscr_ivvl" : "अमान्य दशमलव अंक",
  "lang_jscr_maxm" : "अधिकतम",
  "lang_jscr_maxm_date" : "अधिकतम दिनांक",
  "lang_jscr_minm" : "न्यूनतम",
  "lang_jscr_minm_date" : "न्यूनतम दिनांक",
  "lang_jscr_mint" : "क्षण",
  "lang_jscr_mnth" : "महीना",
  "lang_jscr_msfr" : "प्रपत्र  मे नाम होना जरूरी है",
  "lang_jscr_mslg" : "लॉगिन लापता;",
  "lang_jscr_msob" : "इस फार्म वस्तु का कोई नाम होना चाहिए",
  "lang_jscr_mxdg" : "अंकों की राशि  उम्मीद से अधिक है",
  "lang_jscr_mxvl" : "अधिकतम लंबाई से अधिक है",
  "lang_jscr_nnum" : "ये क्षेत्र सांख्यिक है",
  "lang_jscr_nvlf" : "नकारात्मक संकेत संख्या के बाईं ओर होना चाहिए",
  "lang_jscr_reqr" : "आवश्यक फ़ील्ड",
  "lang_jscr_secd" : "सेकंड",
  "lang_jscr_wfix" : "क्या आप इसे सही करना चाहते हैं?"
};

//-------- Mens USR
