Nm_erro = {
  "lang_jscr_dcml" : "Decimale",
  "lang_jscr_decm" : "Desetinka sekunde",
  "lang_jscr_hour" : "Sat",
  "lang_jscr_iday" : "Dan",
  "lang_jscr_intg" : "Cjelobrojni i",
  "lang_jscr_ivcr" : "Neispravan broj kreditne kartice",
  "lang_jscr_ivdt" : "Neispravan podatak:",
  "lang_jscr_ivem" : "Neispravna E-mail adresa:",
  "lang_jscr_ivnb" : "Neispravan unos broja",
  "lang_jscr_ivtm" : "Neispravan unos vremena:",
  "lang_jscr_ivv2" : "Neispravan podatak:",
  "lang_jscr_ivvl" : "Neispravan unos broja",
  "lang_jscr_maxm" : "Maks",
  "lang_jscr_maxm_date" : "Najviši datum",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Najniži datum",
  "lang_jscr_mint" : "Minute",
  "lang_jscr_mnth" : "Mjesec",
  "lang_jscr_msfr" : "Forma mora imati ime",
  "lang_jscr_mslg" : "Nedostaje prijava;",
  "lang_jscr_msob" : "Ovaj objekt mora imati ime",
  "lang_jscr_mxdg" : "Prevelik broj znamenaka",
  "lang_jscr_mxvl" : "Prošli ste maksimalnu dozvoljenu dužinu",
  "lang_jscr_nnum" : "Polje prihvača samo numeričke vrijednosti",
  "lang_jscr_nvlf" : "Oznaka negativnog broja mora biti sa lijeve strane",
  "lang_jscr_reqr" : "Obavezno polje",
  "lang_jscr_secd" : "Sekunde",
  "lang_jscr_wfix" : "Da li želite ispraviti?"
};

//-------- Mens USR
