Nm_erro = {
  "lang_jscr_dcml" : "소수쩜",
  "lang_jscr_decm" : "쩜일초",
  "lang_jscr_hour" : "시간",
  "lang_jscr_iday" : "날자",
  "lang_jscr_intg" : "정수",
  "lang_jscr_ivcr" : "무효카드",
  "lang_jscr_ivdt" : "무효데이터",
  "lang_jscr_ivem" : "무효이메일",
  "lang_jscr_ivnb" : "무효번호",
  "lang_jscr_ivtm" : "무효시간",
  "lang_jscr_ivv2" : "무효액수",
  "lang_jscr_ivvl" : "무효액수",
  "lang_jscr_maxm" : "최고",
  "lang_jscr_maxm_date" : "최고일",
  "lang_jscr_minm" : "최저",
  "lang_jscr_minm_date" : "최저일",
  "lang_jscr_mint" : "분",
  "lang_jscr_mnth" : "월",
  "lang_jscr_msfr" : "이일에대하여 이름짓기",
  "lang_jscr_mslg" : "로긴이부족함",
  "lang_jscr_msob" : "이일에대하여 이름정하기",
  "lang_jscr_mxdg" : "자리수가더크게",
  "lang_jscr_mxvl" : "최고액수초과",
  "lang_jscr_nnum" : "숫자 아닌 데이터 자리",
  "lang_jscr_nvlf" : "마이나스 표기는 숫자 왠쪽",
  "lang_jscr_reqr" : "의무로써야하는자리",
  "lang_jscr_secd" : "초",
  "lang_jscr_wfix" : "바꾸기를원함니까"
};

//-------- Mens USR
