Nm_erro = {
  "lang_jscr_dcml" : "Dezimalstellen",
  "lang_jscr_decm" : "Zehntelsekunde",
  "lang_jscr_hour" : "Stunde",
  "lang_jscr_iday" : "Tag",
  "lang_jscr_intg" : "Ganzzahlen und",
  "lang_jscr_ivcr" : "Ungültige Kreditkartennummer",
  "lang_jscr_ivdt" : "Ungültige Eingabe:",
  "lang_jscr_ivem" : "Ungültige E-Mail-Adresse",
  "lang_jscr_ivnb" : "Ungültige Ganzzahl",
  "lang_jscr_ivtm" : "Ungültige Zeit",
  "lang_jscr_ivv2" : "Ungültige Eingabedaten",
  "lang_jscr_ivvl" : "Ungültige Dezimalzahl",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Größtes Datum",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Kleinstes Datum",
  "lang_jscr_mint" : "Minuten",
  "lang_jscr_mnth" : "Monat",
  "lang_jscr_msfr" : "Bitte einen Namen für das Formular eingeben",
  "lang_jscr_mslg" : "Login fehlt",
  "lang_jscr_msob" : "Bitte einen Namen für das Formularobjekt eingeben",
  "lang_jscr_mxdg" : "Ziffernanzahl größer als erwartet",
  "lang_jscr_mxvl" : "Maximale Länge überschritten",
  "lang_jscr_nnum" : "Dieses Feld ist numerisch",
  "lang_jscr_nvlf" : "Das Minuszeichen muss links vom Wert stehen",
  "lang_jscr_reqr" : "Pflichtfeld",
  "lang_jscr_secd" : "Sekunden",
  "lang_jscr_wfix" : "- Möchten Sie dies korrigieren?"
};

//-------- Mens USR
