Nm_erro = {
  "lang_jscr_dcml" : "दशांश",
  "lang_jscr_decm" : "एक दुसरा एक दशांश",
  "lang_jscr_hour" : "तास",
  "lang_jscr_iday" : "दिवस",
  "lang_jscr_intg" : "Integers आणि",
  "lang_jscr_ivcr" : "अवैध क्रेडिट कार्ड क्रमांक",
  "lang_jscr_ivdt" : "अवैध डेटा:",
  "lang_jscr_ivem" : "अवैध ईमेल:",
  "lang_jscr_ivnb" : "अवैध पूर्णांक",
  "lang_jscr_ivtm" : "अवैध वेळ:",
  "lang_jscr_ivv2" : "अवैध डेटा:",
  "lang_jscr_ivvl" : "अवैध दशांश",
  "lang_jscr_maxm" : "कमाल",
  "lang_jscr_maxm_date" : "कमाल तारीख",
  "lang_jscr_minm" : "किमान",
  "lang_jscr_minm_date" : "किमान तारीख",
  "lang_jscr_mint" : "मिनिटं",
  "lang_jscr_mnth" : "महिना",
  "lang_jscr_msfr" : "अर्जामध्ये नाव असणे आवश्यक आहे",
  "lang_jscr_mslg" : "गहाळ लॉगिन;",
  "lang_jscr_msob" : "अर्जामध्ये नाव असणे आवश्यक",
  "lang_jscr_mxdg" : "आशे पेक्षा किंमती मधील अंकांची संख्या जास्ती आहे",
  "lang_jscr_mxvl" : "कमाल लांबी जास्ती आहे",
  "lang_jscr_nnum" : "हे क्षेत्र सांख्यिक आहे",
  "lang_jscr_nvlf" : "नकारात्मक संकेत हा किमतीच्या डाव्या बाजूला असायला हवा",
  "lang_jscr_reqr" : "आवश्यक क्षेत्र",
  "lang_jscr_secd" : "सेकंद",
  "lang_jscr_wfix" : "- आपण योग्य इच्छिता?"
};

//-------- Mens USR
