Nm_erro = {
  "lang_jscr_dcml" : "uchích nawempramu",
  "lang_jscr_decm" : "nawémramu musásri",
  "lang_jscr_hour" : "tsanwantan  ankantrí",
  "lang_jscr_iday" : "tsawant",
  "lang_jscr_intg" : "nekápak nuyá",
  "lang_jscr_ivcr" : "Jipitmamu kuit jutai nekapkari. Pénkercha",
  "lang_jscr_ivdt" : "Etserma  nekáscha",
  "lang_jscr_ivem" : "mayainmani  chicham nekátai tusar enkemtai",
  "lang_jscr_ivnb" : "nekápak pénker",
  "lang_jscr_ivtm" : "Tsawantan ankantrí  nekáscha",
  "lang_jscr_ivv2" : "Etserma nekáscha",
  "lang_jscr_ivvl" : "músas nekáscha",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "tsawantá nankánkamuri",
  "lang_jscr_minm" : "ankantán kanáwe",
  "lang_jscr_minm_date" : "nuínchik tsawantak",
  "lang_jscr_mint" : "najánamun etsérin papi",
  "lang_jscr_mnth" : "uwí  nanturi",
  "lang_jscr_msfr" : "Nù  aìmtainkia nàan takùtniuiti",
  "lang_jscr_mslg" : "enkemáyatrik nekanchatai",
  "lang_jscr_msob" : "Jí imiátkinkia.Etsertai papikia chikichik náan  takútniuiti",
  "lang_jscr_mxdg" : "nekapmataai chikkíchik ainia nankás nákamsata",
  "lang_jscr_mxvl" : "nekápka  nánkau",
  "lang_jscr_nnum" : "juinkia nekápkaiti",
  "lang_jscr_nvlf" : "nekáscha etserna nuka nekapka .........  atiniaiti",
  "lang_jscr_reqr" : "takàsmastin utsùmna",
  "lang_jscr_secd" : "ankantán musásri",
  "lang_jscr_wfix" : "nuakma iwiárataj tamek"
};

//-------- Mens USR
